#!/bin/bash
gcc -E $CFILE -o c 

# The script is to run a C file through a preprocessor,
# and save the result in another file.

# **FUNCTIONALITY**
# 1. gcc -E :runs the C file ($CFILE) through the preprocessor bit of the compiler
# 2. -o c :saves the result into another file (c)
